# version: '3.8'

services:
#  interp.log.api:
#    image: zeul/interp.log.api:dev-latest
#    container_name: interp.log.api
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mariadb://maria-db:3306/interplug
#      SPRING_DATASOURCE_USERNAME: dev
#      SPRING_DATASOURCE_PASSWORD: dev
#    depends_on:
#      - maria-db
#    networks:
#      - interp-net

  interp.ia.ap:
    image: zeul/interp.ia.api:dev-latest
    container_name: interp.ia.api
    ports:
      - "1433:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://maria-db:3306/interplug
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: dev
    depends_on:
      maria-db:
        condition: service_healthy
    networks:
      - interp-net

  maria-db:
    image: mariadb:latest
    container_name: maria-db
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=dlsxjvmffjrm
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - interp-vol-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-time-zone=Asia/Seoul
      --default-authentication-plugin=mysql_native_password
    networks:
      - interp-net
    restart: always

networks:
  interp-net:
    driver: bridge

volumes:
  interp-vol-db:
    driver: local

